.TH "NORAA UTM Control" "1" "Jan 2 2022" ""
.SH NAME
NORAA \- UTM/IDS/Firewall Software
.SH SYNOPSIS
.sp
\fBNORAA\fR [ \fB --help \fR]
.sp
.SH "DESCRIPTION"
The
.B NORAA
("Network/Organizational Resource Access Analyzer") UTM Control software allows you to start or restart the program.
The configuration is not done from the command line, rather the configuration file: 
.IR /etc/noraa/noraa.conf.

.SH "FILES"
This is a list of files and a description:

.BI \fB/etc/noraa/noraa.conf\fR 
\-\- The main configuration of the program
.PP
.BI \fB/etc/noraa/deny.conf\fR
\-\- Location of blacklisted IP Addresses. 
.PP
The format is as follows:
.ta 
  <protocol>:<address>
.ta 
e.g: ipv4:8.8.8.8 ipv6:fe80::202b:159:83d4:973
.PP
.BI \fB/var/log/noraa/siglog.log\fR
\-\- Contains the logs of every signature matched
.PP
The format is as follows:
"time" "src:port" -> "dest:port" "protocol" "rulename"
