#!/bin/python3

from hashlib import sha256
username = input("Username: ").strip("\n")
file = open("/etc/npsi/passwd","r")
for line in file:
  if(line.split(":")[0] == username):
    print("User already exists")
    exit(-1)
password = input("Password: ").strip("\n");
repass = input("Re-enter password: ").strip("\n");
if(password != repass):
  print("Passwords do not match")
  exit(-1)
file.close()
appendfile = open("/etc/npsi/passwd","a")
appendfile.write("{}:{}\n".format(username,sha256(password.encode()).hexdigest()));
appendfile.close();
