#!/bin/python3
# 
# Copyright 2021 Conner Macolley
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

from hashlib import sha512
username = input("Username: ").strip("\n")
file = open("/etc/noraa/passwd","r")
for line in file:
  if(line.split(":")[0] == username):
    print("User already exists")
    exit(-1)
pwr= input("Password: ").strip("\n");
repass = input("Re-enter password: ").strip("\n");
if(pwr!= repass):
  print("Passwords do not match")
  exit(-1)
file.close()
appendfile = open("/etc/noraa/passwd","a")
__hash = sha512(pwr.encode()).hexdigest();
ph = "{}:{}\n".format(username,__hash) # lgtm [py/clear-text-storage-sensitive-data]


appendfile.write(ph);
appendfile.close();
