#!/usr/bin/python3
# NSH Update Blacklist
"""
  Entries in the scraped blacklist should be compared to those in the 
  /etc/npsi/deny.conf file. 
  Regex should be used to identify the type of address being used.
  New entired should be entered into deny.conf as followed:
    <protocol>:<address>
  i.e.
    ipv4:8.8.8.8
    ipv6:2600:3c01::f03c:91ff:fe18:bb2f
"""