all: vigil clean
CC=gcc
CFLAGS=-Wall
DIR=./
CLIBS=-l pthread -l ssl -l crypto -l sqlite3 

.ONESHELL:
vigil:
	
	files=`find ./ -name "*\.c" -print | grep -v "task\|vrmc\|lua\|net_host\|test"`
	for i in $$files; do $(CC) -c $(CFLAGS) $$i; done;
	objfiles=`find ./ -name "*\.o" -print`
	$(CC) $(CFLAGS) -g -o vigil.exe $$objfiles $(CLIBS)
	objdump -D vigil.exe -M intel > objdump.txt
	python ../tools/gen_mem_map.py -f objdump.txt
	mv memmap.txt /usr/share/vigil/memmap.txt
	# rm objdump.txt 
	# strip vigil.exe 
clean:
	rm *.o