#!/bin/python3

import socket
import os


if(os.getuid() != 0):
  print("This script requires root privileges")
  exit(-1);

sock = socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
sock.bind(("0.0.0.0",33333))
try:
  while True:
    print(str(sock.recvfrom(1024)[0])[2:-1])
except:
  sock.close()