#!/bin/python3

#   
#   This file is part of Vigil
#   
#   Vigil is free software: you can redistribute it and/or modify it under the terms of the 
#   GNU General Public License as published by the Free Software Foundation, either version 3 
#   of the License, or (at your option) any later version
#   
#   Vigil is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
#   without  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#   See the GNU General Public License for more details
#   You should have received a copy of the GNU General Public License along with Vigil. 
#   If not, see <https://www.gnu.org/licenses/>.
#
# 

from hashlib import sha512
username = input("Username: ").strip("\n")
file = open("/etc/vigil/passwd","r")
for line in file:
  if(line.split(":")[0] == username):
    print("User already exists")
    exit(-1)
pwr= input("Password: ").strip("\n");
repass = input("Re-enter password: ").strip("\n");
if(pwr!= repass):
  print("Passwords do not match")
  exit(-1)
file.close()
appendfile = open("/etc/vigil/passwd","a")
__hash = sha512(pwr.encode()).hexdigest();
ph = "{}:{}\n".format(username,__hash) # lgtm [py/clear-text-storage-sensitive-data]


appendfile.write(ph);
appendfile.close();
